--user data
insert into app_user (id, name, pass) values (1, 'usuario', '$2a$10$UdpP6Jb4emikDOswTBsOu.4958BJCNxc51/RREqVY0P4A4pI1Fh1K');


--tables data
INSERT INTO BOARD (ID, UBICACION_MESA ) VALUES (1,'IZQUIERDA ENTRADA');
INSERT INTO BOARD (ID, UBICACION_MESA ) VALUES (2,'DERECHA ENTRADA');
INSERT INTO BOARD (ID, UBICACION_MESA ) VALUES (3,'TERRAZA IZQUIERDA ENTRADA');
INSERT INTO BOARD (ID, UBICACION_MESA ) VALUES (4,'TERRAZA DERECHA ENTRADA');


--product type data
INSERT INTO PRODUCT_TYPE VALUES (1, 'PLATO DE FONDO');
INSERT INTO PRODUCT_TYPE VALUES (2, 'BEBIDA');
INSERT INTO PRODUCT_TYPE VALUES (3, 'ENSALADA');


--product data
INSERT INTO PRODUCT VALUES (1, 5000, 'TALLARINES CON SALSA ALFREDO', 1);
INSERT INTO PRODUCT VALUES (2, 7000, 'PIZZA MARGARITA', 1);
INSERT INTO PRODUCT VALUES (3, 6500, 'LASAÑA BOLOÑESA', 1);
INSERT INTO PRODUCT VALUES (4, 2000, 'ENSALADA DE TOMATES', 3);
INSERT INTO PRODUCT VALUES (5, 3000, 'ENSALADA PALTA PALMITOS', 3);
INSERT INTO PRODUCT VALUES (6, 1000, 'COCA COLA ZERO', 2);
INSERT INTO PRODUCT VALUES (7, 1000, 'FANTA', 2);
